CREATE TABLE MAE_USUARIO (
    COD_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    TIP_DOCUMENTO NVARCHAR(100),
    VAR_DOC_IDENTIDAD NVARCHAR(100),
    VAR_APELLIDOS NVARCHAR(50),
    VAR_NOMBRE NVARCHAR(50),
    VAR_PASSWORD NVARCHAR(20),
    VAR_NUM_TELEFONO NVARCHAR(15),
    INT_FLG_ELIMINADO INT,
    FEC_REGISTRO DATE,
    FEC_MODIFICACION DATE
);

CREATE TABLE DET_USUARIO_EMPRESA (
    COD_EMPRESA INT PRIMARY KEY IDENTITY(1,1),
    COD_USUARIO INT,
    VAR_CARGO NVARCHAR(100),
    VAR_CORREO NVARCHAR(100),
    INT_ESTADO INT,
    VAR_NOM_IMAGEN NVARCHAR(100),
    INT_FLG_ELIMINADO INT,
    FEC_REGISTRO DATE,
    FEC_MODIFICACION DATE,
    CONSTRAINT FK_COD_USUARIO FOREIGN KEY (COD_USUARIO) REFERENCES MAE_USUARIO(COD_USUARIO)
);